baseURL = "https://example.org/"
languageCode = "ru"
title = "О стране и мире: Российские реалии 2023"
theme = "conference2023_theme"
relativeURLS = true

[module]
    [[module.mounts]]
        source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
        target = "assets/js/bootstrap.bundle.min.js"